stages:
  - version
  - release

variables:
  AUTHOR: 'Ali Zahedigol'

.node: &node
  image: node:latest
  tags:
    - node

.python: &python
  image: python:3.7
  tags:
    - python


version:
  # Requires Node >= 10.13 version
  <<: *node
  stage: version
  only:
    refs:
    - master
    - develop
  script:
    - npm install @semantic-release/gitlab @semantic-release/exec @semantic-release/changelog
    - npx semantic-release --generate-notes false --dry-run
    - npx semantic-release
  artifacts:
    paths:
    - VERSION.txt

release:
  <<: *python
  stage: production
  environment:
    name: production
  script:
    - echo "Version is $(cat VERSION.txt)"
    - sed -i "s/version='1.0.0',/version='$(cat VERSION.txt)',/g" setup.py
    - pip install twine
    - python setup.py sdist bdist_wheel
    - TWINE_PASSWORD=${TWINE_TOKEN} TWINE_USERNAME=${TWINE_USERNAME} python -m twine upload dist/*
  only:
    - master
    - develop
  dependencies:
    - version

