stages:
  - version
  - release

variables:
  AUTHOR: 'Ali Zahedigol'

.node: &node
  image: node:latest
  tags:
    - node

.python: &python
  image: python:3.7
  tags:
    - python


version:
  # Requires Node >= 10.13 version
  <<: *node
  stage: version
  only:
    refs:
    - master
    - develop
  script:
    - npm install @semantic-release/gitlab @semantic-release/exec @semantic-release/changelog
    - npx semantic-release --generate-notes false --dry-run
    - npx semantic-release
  artifacts:
    paths:
    - VERSION.txt

release:
  <<: *python
  stage: release
  environment:
    name: release
  script:
    - echo "Version is $(cat VERSION.txt)"
    - sed -i "s/__version__ = \"1.0.0\"/__version__ = \"$(cat VERSION.txt)\"/g" azbankgateways/__init__.py
    - pip install build twine
    - python -m build
    - TWINE_PASSWORD=${TWINE_TOKEN} TWINE_USERNAME=${TWINE_USERNAME} python -m twine upload dist/*
  only:
    - master
    - develop
  dependencies:
    - version

